# Generated by Django 3.0.3 on 2020-02-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('cliente', models.CharField(max_length=256)),
                ('arquivo', models.FileField(upload_to='')),
            ],
        ),
    ]
